//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WCFServiceWebRole1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class nataliaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new nataliaEntities object using the connection string found in the 'nataliaEntities' section of the application configuration file.
        /// </summary>
        public nataliaEntities() : base("name=nataliaEntities", "nataliaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new nataliaEntities object.
        /// </summary>
        public nataliaEntities(string connectionString) : base(connectionString, "nataliaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new nataliaEntities object.
        /// </summary>
        public nataliaEntities(EntityConnection connection) : base(connection, "nataliaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CentrosCom> CentrosComs
        {
            get
            {
                if ((_CentrosComs == null))
                {
                    _CentrosComs = base.CreateObjectSet<CentrosCom>("CentrosComs");
                }
                return _CentrosComs;
            }
        }
        private ObjectSet<CentrosCom> _CentrosComs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CentrosComs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCentrosComs(CentrosCom centrosCom)
        {
            base.AddObject("CentrosComs", centrosCom);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="nataliaModel", Name="CentrosCom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CentrosCom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CentrosCom object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="direccion">Initial value of the Direccion property.</param>
        /// <param name="localidad">Initial value of the Localidad property.</param>
        public static CentrosCom CreateCentrosCom(global::System.Int32 id, global::System.String nombre, global::System.String direccion, global::System.String localidad)
        {
            CentrosCom centrosCom = new CentrosCom();
            centrosCom.ID = id;
            centrosCom.Nombre = nombre;
            centrosCom.Direccion = direccion;
            centrosCom.Localidad = localidad;
            return centrosCom;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Localidad
        {
            get
            {
                return _Localidad;
            }
            set
            {
                OnLocalidadChanging(value);
                ReportPropertyChanging("Localidad");
                _Localidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Localidad");
                OnLocalidadChanged();
            }
        }
        private global::System.String _Localidad;
        partial void OnLocalidadChanging(global::System.String value);
        partial void OnLocalidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Tiendas
        {
            get
            {
                return _Tiendas;
            }
            set
            {
                OnTiendasChanging(value);
                ReportPropertyChanging("Tiendas");
                _Tiendas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tiendas");
                OnTiendasChanged();
            }
        }
        private Nullable<global::System.Int32> _Tiendas;
        partial void OnTiendasChanging(Nullable<global::System.Int32> value);
        partial void OnTiendasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cine
        {
            get
            {
                return _Cine;
            }
            set
            {
                OnCineChanging(value);
                ReportPropertyChanging("Cine");
                _Cine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cine");
                OnCineChanged();
            }
        }
        private global::System.String _Cine;
        partial void OnCineChanging(global::System.String value);
        partial void OnCineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion

    
    }

    #endregion

    
}
