//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercado
    {
        public int IdProducto { get; set; }
        public string Categoria { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Medida { get; set; }
        public Nullable<int> IdUser { get; set; }
    }
}
